export const theme = {
   colors: {
      background: "#0a0f1f",
      card: "#111a35",
      text: "#ffffff",
      textSecondary: "#c2c7d4",
      textMuted: "#9aa3b6",
      inputBackground: "#161f38",
      inputText: "#f7f9ff",
      placeholder: "#888",
      primary: "#5178ee",
      socialButton: "#ffffff",
      socialButtonAlt: "#1f2842",
      socialText: "#111a35",
      orText: "#7380a1",
      footerText: "#7a86a0",
      footerLink: "#d1e1ff",
      shadow: "#000",
   },
   borderRadius: {
      card: 24,
      input: 16,
      button: 16,
   },
   fontSize: {
      title: 28,
      subtitle: 15,
      label: 13,
      input: 16,
      button: 16,
      social: 15,
      footer: 13,
      or: 14,
   },
   fontWeight: {
      bold: "700",
   } as const,
   spacing: {
      pagePadding: 24,
      cardPadding: 28,
      inputPaddingHorizontal: 16,
      inputPaddingVertical: 14,
      buttonPaddingVertical: 16,
      socialButtonPaddingVertical: 14,
      marginBottomTitle: 8,
      marginBottomSubtitle: 24,
      marginBottomInputGroup: 16,
      marginBottomLabel: 8,
      marginTopButton: 8,
      marginVerticalOr: 18,
      gapSocialRow: 12,
      marginTopFooter: 22,
   },
   shadow: {
      offset: { width: 0, height: 12 },
      opacity: 0.2,
      radius: 24,
      elevation: 10,
   },
};
