create table movies (
    id bigint generated by default as identity primary key,
    name text,
    description text
);

alter table movies enable row level security;

create policy "Authenticated users can select movies"
on movies
for select
to authenticated
using (true);

create policy "Authenticated users can insert movies"
on movies
for insert
to authenticated
with check (true);

create policy "Authenticated users can update movies"
on movies
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete movies"
on movies
for delete
to authenticated
using (true);
